server:
  port: 8090
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

tushare:
  token: ""

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/piao?connectTimeout=3&socketTimeout=10
    username: postgres
    password: PG@123456
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 5000
      validation-timeout: 3000
      initialization-fail-timeout: 0
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      continue-on-error: true
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
    livereload:
      enabled: true

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
